services:
  backend:
    image: ${DOCKERHUB_USERNAME}/leanx-erp-system-backend:latest
    container_name: leanx-backend
    ports: 
      - 80:8080
    environment:
      RDS_MYSQL_ENDPOINT: ${RDS_MYSQL_ENDPOINT}
      RDS_MYSQL_PORT: ${RDS_MYSQL_PORT}
      RDS_MYSQL_USER: ${RDS_MYSQL_USER}
      RDS_MYSQL_PASSWORD: ${RDS_MYSQL_PASSWORD}
    networks:
      - leanx_network
    expose:
      - "8080"

  # frontend:
  #   image: ${DOCKERHUB_USERNAME}/leanx-erp-system-frontend:latest
  #   container_name: leanx-frontend
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - leanx_network

networks:
  leanx_network:
    driver: bridge