services:
  frontend-server:
    image: ${DOCKERHUB_USERNAME}/leanx-erp-system-frontend:latest
    container_name: leanx-frontend
    restart: always # ensures restarts on failure
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
    - leanx_network

  backend-server:
    image: ${DOCKERHUB_USERNAME}/leanx-erp-system-backend:latest
    container_name: leanx-backend
    restart: always
    environment:
      RDS_MYSQL_ENDPOINT: ${RDS_MYSQL_ENDPOINT}
      RDS_MYSQL_PORT: ${RDS_MYSQL_PORT}
      RDS_MYSQL_USER: ${RDS_MYSQL_USER}
      RDS_MYSQL_PASSWORD: ${RDS_MYSQL_PASSWORD}
      RDS_MYSQL_DB_NAME: ${RDS_MYSQL_DB_NAME}
    networks:
      - leanx_network
    expose:
      - "8080"

networks:
  leanx_network:
    driver: bridge