version: '3.8'

services:
  web-server:  # Nginx reverse proxy
    image: nginx:alpine
    container_name: leanx-web-server
    restart: always
    ports:
      - "80:80" 
    depends_on:
      - backend-server
      - frontend-server
    networks:
      - leanx_network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount custom Nginx config

  frontend-server:  # Next.js App (Internal only)
    image: ${DOCKERHUB_USERNAME}/leanx-erp-system-frontend:latest
    container_name: leanx-frontend
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - backend-server
    networks:
      - leanx_network
    expose:
      - "3000"

  backend-server:  # Backend Server (Internal only)
    image: ${DOCKERHUB_USERNAME}/leanx-erp-system-backend:latest
    container_name: leanx-backend
    restart: always
    environment:
      RDS_MYSQL_ENDPOINT: ${RDS_MYSQL_ENDPOINT}
      RDS_MYSQL_PORT: ${RDS_MYSQL_PORT}
      RDS_MYSQL_USER: ${RDS_MYSQL_USER}
      RDS_MYSQL_PASSWORD: ${RDS_MYSQL_PASSWORD}
      RDS_MYSQL_DB_NAME: ${RDS_MYSQL_DB_NAME}
    networks:
      - leanx_network
    expose:
      - "8080"

networks:
  leanx_network:
    driver: bridge