services:
  backend:
    image: ${DOCKERHUB_USERNAME}/leanx-erp-system-backend:latest
    container_name: leanx-backend
    ports: 
      - 80:8080
    env_file:
      - .env
    networks:
      - leanx_network
    expose:
      - "8080"

  # frontend:
  #   image: ${DOCKERHUB_USERNAME}/leanx-erp-system-frontend:latest
  #   container_name: leanx-frontend
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - leanx_network

networks:
  leanx_network:
    driver: bridge