services:
  dev-web-server:  # Nginx reverse proxy
    image: nginx:alpine
    container_name: leanx-web-server
    restart: unless-stopped
    ports:
      - "80:80" 
    depends_on:
      - dev-backend-server
      - dev-frontend-server
      - dev-db-server
    networks:
      - leanx_network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount custom Nginx config

  dev-frontend-server:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: leanx-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    depends_on:
      - dev-backend-server
      - dev-db-server
    networks:
      - leanx_network
    expose:
      - "3000"

  dev-backend-server:
    build:
      context: ../backend
      dockerfile: Dockerfile 
    container_name: leanx-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      RDS_MYSQL_ENDPOINT: dev-db-server
      RDS_MYSQL_PORT: 3306
      RDS_MYSQL_USER: devusr
      RDS_MYSQL_PASSWORD: devpassword
      RDS_MYSQL_DB_NAME: leanx_erp_dev
      SMTP_USERNAME: it.support@lean-x.de
      SMTP_PASSWORD: Bealis36.de@@ionos
      SMTP_HOST: smtp.ionos.de
    depends_on:
      - dev-db-server
    networks:
      - leanx_network

  dev-db-server:
    image: mysql:8.0
    container_name: leanx-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: devusr
      MYSQL_PASSWORD: devpassword
      MYSQL_DATABASE: leanx_erp_dev
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - leanx_network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


networks:
  leanx_network:
    driver: bridge