name: CI/CD-Pipeline (Build -> Test -> Deploy) - DEV ENVIRONMENT

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build application and push to Dockerhub
        run: |
          chmod +x ./scripts/build-backend.sh
          ./scripts/build-backend.sh
        working-directory: ${{ github.workspace }} 
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build application and push to Dockerhub
        run: |
          chmod +x ./scripts/build-frontend.sh
          ./scripts/build-frontend.sh
        working-directory: ${{ github.workspace }} 
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
  
  test:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run application tests
        run: |
          chmod +x ./scripts/test.sh
          ./scripts/test.sh
        working-directory: ${{ github.workspace }} 
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        continue-on-error: false


  deploy:
    needs: [build-backend, build-frontend, test]
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy Application to EC2
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh
        working-directory: ${{ github.workspace }} 
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          EC2_USER: ${{ vars.EC2_USER }}
          EC2_ELASTIC_IP: ${{ vars.EC2_ELASTIC_IP }}
          AWS_EC2_ACCESS_KEY: ${{ secrets.AWS_EC2_ACCESS_KEY }}
          RDS_MYSQL_USER: ${{ secrets.RDS_MYSQL_USER }}
          RDS_MYSQL_PASSWORD: ${{ secrets.RDS_MYSQL_PASSWORD }}
          RDS_MYSQL_ENDPOINT: ${{ vars.RDS_MYSQL_ENDPOINT }}
          RDS_MYSQL_PORT: ${{ vars.RDS_MYSQL_PORT }}
          RDS_MYSQL_DB_NAME: ${{ vars.RDS_MYSQL_DB_NAME }}
