name: CI/CD-Pipeline (Build, Test and Deploy)

# Controls when the workflow will run
on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -f backend/pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: backend 
          file: backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/leanx-erp-system-backend:latest
          build-args:
            JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
            RDS_MYSQL_USER: ${{ secrets.RDS_MYSQL_USER }}
            RDS_MYSQL_PASSWORD: ${{ secrets.RDS_MYSQL_PASSWORD }}
            RDS_MYSQL_ENDPOINT: ${{ vars.RDS_MYSQL_ENDPOINT }}
            RDS_MYSQL_PORT: ${{ vars.RDS_MYSQL_PORT }}


  deploy:
    runs-on: ubuntu-latest
    needs: [build]
   
    steps:
      # Step 4: Deploy Application to EC2
      - name: Deploy Application
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh
        env:
          AWS_EC2_ACCESS_KEY: ${{ secrets.AWS_EC2_ACCESS_KEY }}    
